%\VignetteIndexEntry{R / Bioconductor for High Throughput Sequence Analysis}

\documentclass[a4paper]{article}

%\SweaveOpts{pdf=FALSE, png=TRUE}

%% bioc style
<<style-Sweave, eval=TRUE, echo=FALSE, results=tex>>=
BiocStyle::latex()
@

%% title
\title{easyRNASeq - a package for simple RNA-Seq quantification}
\author{
  Nicolas Delhomme\footnote{\href{mailto:nicolas.delhomme@umu.se}{
  nicolas.delhomme@umu.se}}\\
  Bastian Schiffthaler\footnote{\href{mailto:bastian.schiffthaler@umu.se}{
  bastian.schiffthaler@umu.se}}\\
}

\date{\today}

%% doc
\begin{document}
\SweaveOpts{concordance=TRUE}
\maketitle

\section{Where to find the real vignette}
This vignette is just a place-holder, to access the tutorial do:

<<open the URL, eval=FALSE>>=
browseURL(system.file(package="easyRNASeq","doc","simpleRNASeq.html"))
@

\end{document}
